APPLY_PREPROCESSING_TO_SIMULATIONS: true
PROTOCOLS_TO_VISUALIZE:
-   - 200
    - 4
    - 240
    - 5
    - 0.05
-   - 10
    - 10
    - 240
    - 8
    - 0.05
-   - 230
    - 1
    - 240
    - 2
    - 0.05
DATA_PATH: C:\Users\alexa\experimental_data\todos\ENTRADAS_PATRICIA
BASE_OUTPUT_DIR: ./protocol_visualizations/
FILTER_TYPE: custom
ARTIFACT_REJECTION_TYPE: null
APPLY_NOTCH_FILTER: false
APPLY_MEAN_REMOVAL: true
REMOVE_FIRST_TWO_WINDOWS: true
CUSTOM_FILTER_PARAMS:
    low: 30.0
    high: 300.0
    order: 2
PERCENTILE_REMOVAL_AMOUNT: 10
ARTIFACT_THRESHOLDS:
    uni_BSPC2021: 4.0e-05
    legacy: 0.0005
TARGET_ELECTRODES: Fz
AVAILABLE_ELECTRODES:
- Fz
- F3
- F4
- F7
- Fcz
- Cz
- C3
- C4
- Pz
- P3
- P4
- T3
- T4
- T5
- T6
- Oz
SIGNAL_FREQUENCIES:
- 81
- 85
- 89
- 93
- 83
- 87
- 91
- 95
NOISE_FREQUENCIES:
- 131
- 137
- 149
- 151
- 157
- 163
- 167
- 173
